definitions:
  services:
    docker:
      memory: 3072
  steps:

    - step: &docker-build
        name: docker build
        image: atlassian/pipelines-awscli
        services:
          - docker
        size: 2x
        caches:
          - docker
        script:
          - export IMAGE_TAG="${BITBUCKET_COMMIT::7}"
          - bash deployment/dockerbuild.sh

    - step: &k8s-deployment
        name: proxy deployment
        trigger: manual
        image: vietduy0509/deployer:latest
        services:
          - docker
        script:
          - export IMAGE_TAG="${BITBUCKET_COMMIT::7}" && export NAMESPACE=nginx-proxy && export EKS_CLUSTER="devops-eks"
          - cd deployment && bash deploy.sh

image: python:3.9
pipelines:
  branches:
    master:
      - step: *docker-build
      - step: *k8s-deployment